name: Increment Patch Version

on:
  workflow_dispatch:
      
jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.5.1
        with:
          sdk: stable

      - name: Increment Version
        run: |
          # Estrapola la versione corrente da pubspec.yaml
          current_version=$(grep 'version:' pubspec.yaml | awk '{print $2}')

          # Dividi la versione in componenti major, minor e patch
          major=$(echo $current_version | cut -d. -f1)
          minor=$(echo $current_version | cut -d. -f2)
          patch=$(echo $current_version | cut -d. -f3)

          # Incrementa la patch
          patch=$((patch + 1))

          # Crea la nuova versione
          new_version="$major.$minor.$patch"

          # Sostituisci la vecchia versione con la nuova in pubspec.yaml
          sed -i "s/version: $current_version/version: $new_version/" pubspec.yaml

          # Commit e push delle modifiche
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Increment version to $new_version" pubspec.yaml
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
